// SPDX-License-Identifier: AGPL-3.0-or-later

package webhook

import (
	"os"
	"regexp"
	"sort"
	"strings"
	"testing"
)

// The two install paths declare webhooks separately:
//
//   - config/webhook/manifests.yaml is generated by controller-gen from
//     the +kubebuilder:webhook markers, so it is the source of truth.
//   - config/helm/keystone-operator/templates/validatingwebhookconfiguration.yaml
//     is hand-maintained, and every ArgoCD Application installs through it.
//
// Nothing kept them in step. vauditentry.kb.io was present in the
// generated manifest and absent from the chart, so the append-only
// enforcement backing the compliance mappings was not registered on any
// chart-based cluster — silently, because a webhook that is not
// installed raises nothing.
//
// hack/lockstep guards whole resources by name and cannot see inside a
// ValidatingWebhookConfiguration, so this test guards the webhook set.
//
// The chart file is a Go template and will not parse as YAML, but
// webhook names are plain literals in both files, so both are scanned
// for the same `name: v<something>.kb.io` shape.

var webhookNameRE = regexp.MustCompile(`(?m)^\s*-?\s*name:\s*(v[a-z0-9]+\.kb\.io)\s*$`)

func webhookNamesIn(t *testing.T, path string) []string {
	t.Helper()
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	matches := webhookNameRE.FindAllStringSubmatch(string(raw), -1)
	if len(matches) == 0 {
		// A scan that silently finds nothing would make this test pass
		// for the wrong reason, which is the exact failure mode it
		// exists to prevent.
		t.Fatalf("found no webhook names in %s — the scan pattern is broken, "+
			"not the manifests", path)
	}
	names := make([]string, 0, len(matches))
	for _, m := range matches {
		names = append(names, m[1])
	}
	sort.Strings(names)
	return names
}

func TestWebhookManifestsAndHelmChartDeclareTheSameWebhooks(t *testing.T) {
	const (
		generated = "../../config/webhook/manifests.yaml"
		chart     = "../../config/helm/keystone-operator/templates/validatingwebhookconfiguration.yaml"
	)

	want := webhookNamesIn(t, generated)
	got := webhookNamesIn(t, chart)

	if strings.Join(want, ",") == strings.Join(got, ",") {
		return
	}

	inWant := map[string]bool{}
	for _, n := range want {
		inWant[n] = true
	}
	inGot := map[string]bool{}
	for _, n := range got {
		inGot[n] = true
	}

	for _, n := range want {
		if !inGot[n] {
			t.Errorf("%s is generated by controller-gen but missing from the helm chart: "+
				"every chart-based install (i.e. every ArgoCD Application) runs without it", n)
		}
	}
	for _, n := range got {
		if !inWant[n] {
			t.Errorf("%s is declared in the helm chart but not generated by controller-gen: "+
				"the chart registers a webhook path the manager may not serve", n)
		}
	}
}
