// SPDX-License-Identifier: Apache-2.0

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// SchemaDefinition is Keystone's declarative schema-as-code API — the
// Atlas-parity piece. Instead of hand-writing a MigrationBundle with
// SQL, authors describe the desired schema shape and the
// SchemaDefinitionReconciler computes the diff against the live
// observed state and auto-generates a MigrationBundle with the
// necessary DDL.
//
// This is the Phase 10 flagship feature. The type is committed in
// Phase 10.1 (this file); the differ lands in Phase 10.2; the
// reconciler in Phase 10.3.

// ColumnType is the allowed set of column types. Restricted from "any
// string" to a whitelist so the API can't be abused to inject DDL via
// the type field. New types land via API review.
//
// +kubebuilder:validation:MaxLength=128
// +kubebuilder:validation:Pattern=`^[a-z][a-z0-9_ (),\[\]]*$`
type ColumnType string

// DesiredColumn is one column declaration.
type DesiredColumn struct {
	// Name is the column identifier.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:Pattern=`^[a-z_][a-z0-9_]*$`
	Name string `json:"name"`

	// Type is the PostgreSQL data type (no default — every column must
	// declare it explicitly).
	//
	// +kubebuilder:validation:Required
	Type ColumnType `json:"type"`

	// Nullable controls NOT NULL. Default true because declaring a
	// NOT NULL column without a default on an existing populated table
	// requires a backfill dance; the differ will refuse to plan that.
	//
	// `omitempty` was removed deliberately: keystonectl-inspect-generated
	// SchemaDefinitions emit `nullable: false` for NOT NULL columns; with
	// `omitempty` the false value would be stripped from JSON, K8s would
	// then apply the kubebuilder default of `true` at admission, and
	// every NOT NULL column would round-trip into the cluster as nullable
	// — producing thousands of bogus ALTER TABLE ops on every reconcile.
	// Always emit the field so the admission defaulter only fires when
	// the user genuinely omits it.
	//
	// +kubebuilder:default=true
	Nullable bool `json:"nullable"`

	// Default is the column DEFAULT clause. Empty = no default.
	//
	// +optional
	// +kubebuilder:validation:MaxLength=512
	Default string `json:"default,omitempty"`

	// PrimaryKey marks the column as the table's single-column PK.
	// For composite PKs, use DesiredTable.PrimaryKey instead.
	//
	// +optional
	PrimaryKey bool `json:"primaryKey,omitempty"`

	// Identity declares the column as a PostgreSQL identity column:
	// `GENERATED ALWAYS AS IDENTITY` or `GENERATED BY DEFAULT AS
	// IDENTITY`. Empty means an ordinary column.
	//
	// The two spellings are not cosmetic. Under ALWAYS, PostgreSQL
	// rejects a user-supplied value unless the INSERT says OVERRIDING
	// SYSTEM VALUE; under BY DEFAULT the user's value wins. Collapsing
	// them would silently change whether an application's inserts are
	// accepted, so the distinction is carried through the desired state
	// rather than normalised away.
	//
	// Values are the SQL keywords rather than CamelCase, matching the
	// rest of this API (ColumnType carries raw PostgreSQL type names,
	// DesiredIndex.Method carries "btree"), and matching what the
	// inspector reads back out of pg_attribute.attidentity.
	//
	// Identity implies NOT NULL — PostgreSQL marks such columns NOT NULL
	// automatically — but it does NOT imply uniqueness: a sequence can be
	// reset or a value inserted by hand, so a PRIMARY KEY or UNIQUE
	// constraint is still required to guarantee it.
	//
	// +optional
	// +kubebuilder:validation:Enum="";ALWAYS;"BY DEFAULT"
	Identity string `json:"identity,omitempty"`

	// Generated is the expression of a STORED generated column —
	// `GENERATED ALWAYS AS (<expr>) STORED`. Empty means an ordinary
	// column.
	//
	// Only STORED is modelled. PostgreSQL had no other kind before 18,
	// and the inspector reads the expression back from a stored column;
	// when VIRTUAL becomes a target, it arrives as a sibling field rather
	// than by overloading this one.
	//
	// Mutually exclusive with Default and with Identity: a generated
	// column computes its value, so a DEFAULT or an identity sequence has
	// nothing to apply to.
	//
	// +optional
	// +kubebuilder:validation:MaxLength=2048
	Generated string `json:"generated,omitempty"`
}

// DesiredIndex is one index declaration.
//
// Three column-spec shapes are supported (use exactly one):
//   1. Columns []string                 — simple; one btree col per entry,
//                                          ASC default, no opclass.
//   2. ColumnRefs []DesiredIndexColumn   — rich; per-column ASC/DESC,
//                                          NULLS FIRST/LAST, opclass.
//   3. Expression string                 — single expression-index body
//                                          (e.g. "lower(email)" or
//                                          "coalesce(deleted_at, 'epoch')").
//
// All four index features unblocked by this set:
//   - sort direction per column          (ColumnRefs[i].Direction)
//   - expression indexes                 (Expression)
//   - covering / INCLUDE columns         (Include)
//   - per-column opclass                 (ColumnRefs[i].OpClass)
//   - partial-index predicate            (Where, already present)
//
// Designed for backwards compat: existing CRs using `Columns []string`
// keep working unchanged. The Webhook validator (Phase 4 — separate
// concern) enforces "exactly one of Columns/ColumnRefs/Expression".
type DesiredIndex struct {
	// Name of the index.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:Pattern=`^[a-z_][a-z0-9_]*$`
	Name string `json:"name"`

	// Columns the index covers, in order. Simple form: one btree column
	// per entry, ASC sort, no opclass. Mutually exclusive with
	// ColumnRefs and Expression.
	//
	// +optional
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:MaxItems=32
	Columns []string `json:"columns,omitempty"`

	// ColumnRefs is the rich-form column list. Each entry can specify
	// per-column sort direction (ASC/DESC), null ordering (NULLS FIRST/
	// LAST), and operator class (e.g. varchar_pattern_ops for LIKE
	// optimisation). Mutually exclusive with Columns and Expression.
	//
	// +optional
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:MaxItems=32
	ColumnRefs []DesiredIndexColumn `json:"columnRefs,omitempty"`

	// Expression is a single index-expression body, used for expression
	// indexes like CREATE INDEX foo ON t (lower(email)). The string is
	// emitted verbatim wrapped in parens; do NOT include `CREATE INDEX`
	// or column-list parens. Mutually exclusive with Columns and
	// ColumnRefs.
	//
	// +optional
	// +kubebuilder:validation:MaxLength=1024
	Expression string `json:"expression,omitempty"`

	// Include is the optional INCLUDE clause for covering indexes
	// (PostgreSQL 11+). Listed columns are stored in the index leaf
	// pages but not used as the index key, enabling index-only scans
	// for queries that select these columns alongside an index probe.
	// Method MUST be btree (PG limitation).
	//
	// +optional
	// +kubebuilder:validation:MaxItems=32
	Include []string `json:"include,omitempty"`

	// Unique controls UNIQUE constraint on the index.
	//
	// +optional
	Unique bool `json:"unique,omitempty"`

	// NullsNotDistinct controls how NULL values are deduplicated in a
	// UNIQUE index (PostgreSQL 15+). Default behaviour (NULLS DISTINCT)
	// treats every NULL as distinct, allowing many rows with NULL in
	// the indexed column. NULLS NOT DISTINCT treats all NULLs as equal
	// for uniqueness — at most one row may have NULL.
	//
	// Only meaningful when Unique=true. Ignored otherwise.
	//
	// +optional
	NullsNotDistinct bool `json:"nullsNotDistinct,omitempty"`

	// Method selects the PG index method (btree default, gin, gist,
	// hash, brin, spgist). INCLUDE only valid with btree.
	//
	// +kubebuilder:default="btree"
	// +kubebuilder:validation:Enum=btree;hash;gin;gist;brin;spgist
	Method string `json:"method,omitempty"`

	// Where is an optional partial-index predicate. The string is
	// emitted verbatim after the WHERE keyword; do NOT include the
	// keyword itself.
	//
	// +optional
	// +kubebuilder:validation:MaxLength=1024
	Where string `json:"where,omitempty"`
}

// DesiredIndexColumn is one column entry in DesiredIndex.ColumnRefs.
//
// Exactly one of Name or Expression must be set. Name is for direct
// column references (the common case); Expression is for per-column
// SQL expressions like `lower(email)` or `coalesce(rule_value, '')`.
// PostgreSQL allows mixing column refs and expressions in a single
// multi-column index — this struct accommodates either shape.
type DesiredIndexColumn struct {
	// Name of the column. Quoted as identifier on render. Mutually
	// exclusive with Expression.
	//
	// +optional
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:Pattern=`^[a-z_][a-z0-9_]*$`
	Name string `json:"name,omitempty"`

	// Expression is a per-column SQL expression body (e.g.
	// `coalesce(col, '')` or `lower(email)`). The renderer wraps it
	// in parens. Mutually exclusive with Name. Type-cast literals
	// like `'x'::uuid` and function calls are permitted; the bodies
	// are emitted verbatim — operator MUST treat them as
	// trusted-input (in practice keystonectl-inspect generates them
	// from pg_get_indexdef which is the SOURCE OF TRUTH from the
	// live database).
	//
	// +optional
	// +kubebuilder:validation:MaxLength=1024
	Expression string `json:"expression,omitempty"`

	// Direction selects the per-column sort order. PG default is asc;
	// desc materially changes the index for ORDER BY queries.
	//
	// No `+kubebuilder:default` marker — apiserver-side defaulting
	// materialises the field on every stored object even when the
	// source omits it, which then surfaces as spurious drift to
	// SSA-based diff (every Argo sync reports OutOfSync because git
	// has no `direction` field while live has `direction: asc`). The
	// differ already treats the empty string as "asc" semantically
	// (see internal/migration/declarative/differ.go renderIndexColumn),
	// so the marker added behaviour the differ doesn't need but the
	// admission path materialised verbosely.
	//
	// +optional
	// +kubebuilder:validation:Enum=asc;desc
	Direction string `json:"direction,omitempty"`

	// Nulls selects null ordering. PG default depends on Direction
	// (asc -> nulls last; desc -> nulls first). Override here if the
	// query plans need a non-default placement.
	//
	// +optional
	// +kubebuilder:validation:Enum=first;last
	Nulls string `json:"nulls,omitempty"`

	// OpClass is an optional per-column operator class. Common cases:
	//   varchar_pattern_ops    — LIKE 'prefix%' optimisation
	//   text_pattern_ops       — same for text columns
	//   gin_trgm_ops           — pg_trgm fuzzy match
	//   jsonb_path_ops         — JSON @> queries on jsonb cols
	// The string is emitted verbatim as a quoted identifier.
	//
	// +optional
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:Pattern=`^[a-z_][a-z0-9_]*$`
	OpClass string `json:"opClass,omitempty"`
}

// DesiredForeignKey is one foreign key declaration.
type DesiredForeignKey struct {
	// Name of the constraint.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:Pattern=`^[a-z_][a-z0-9_]*$`
	Name string `json:"name"`

	// Columns in this table referencing the target.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:MaxItems=8
	Columns []string `json:"columns"`

	// ReferencesTable is the target table name (same schema as the
	// containing SchemaDefinition — cross-schema FKs are deliberately
	// out of scope for v1alpha1).
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:Pattern=`^[a-z_][a-z0-9_]*$`
	ReferencesTable string `json:"referencesTable"`

	// ReferencesColumns is the target column list.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:MaxItems=8
	ReferencesColumns []string `json:"referencesColumns"`

	// OnDelete action — CASCADE, SET NULL, SET DEFAULT, RESTRICT, NO ACTION.
	//
	// +kubebuilder:default="NO ACTION"
	// +kubebuilder:validation:Enum=CASCADE;SET NULL;SET DEFAULT;RESTRICT;NO ACTION
	OnDelete string `json:"onDelete,omitempty"`
}

// DesiredTable describes one table's desired shape.
type DesiredTable struct {
	// Name of the table.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:Pattern=`^[a-z_][a-z0-9_]*$`
	Name string `json:"name"`

	// Columns is the ordered list of columns.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:MaxItems=128
	Columns []DesiredColumn `json:"columns"`

	// PrimaryKey is the composite primary-key column list. Use this for
	// multi-column PKs; single-column PKs can also use
	// DesiredColumn.PrimaryKey as a shorthand.
	//
	// +optional
	// +kubebuilder:validation:MaxItems=8
	PrimaryKey []string `json:"primaryKey,omitempty"`

	// Indexes declared on this table.
	//
	// +optional
	// +kubebuilder:validation:MaxItems=32
	Indexes []DesiredIndex `json:"indexes,omitempty"`

	// ForeignKeys declared on this table.
	//
	// +optional
	// +kubebuilder:validation:MaxItems=32
	ForeignKeys []DesiredForeignKey `json:"foreignKeys,omitempty"`

	// EnableRLS enables row-level security on this table. When true,
	// the differ emits ALTER TABLE ... ENABLE ROW LEVEL SECURITY.
	// Policies are declared in spec.policies[].
	//
	// +optional
	EnableRLS bool `json:"enableRLS,omitempty"`

	// ForceRLS controls whether row-level security also applies to the
	// table's OWNER (ALTER TABLE ... FORCE ROW LEVEL SECURITY). Ignored
	// unless EnableRLS is true.
	//
	// Unset means true. That default is deliberate and is the safe one:
	// PostgreSQL exempts a table's owner from its own policies, so
	// ENABLE-without-FORCE leaves every policy in place while enforcing
	// none of them against an application that connects as the owning role
	// — which is the ordinary deployment shape. A field that defaulted to
	// false would mean a SchemaDefinition asking for row-level security
	// got, silently, a schema that did not enforce it.
	//
	// It is a pointer so that "unset" and "explicitly false" are
	// distinguishable. Explicitly false is a real configuration — it fits a
	// schema whose owner is a migration role that must retain unrestricted
	// access — and it is honoured, but it has to be asked for. Before this
	// field existed the differ emitted FORCE unconditionally alongside
	// ENABLE, so leaving it unset preserves exactly that behaviour and no
	// existing SchemaDefinition changes meaning.
	//
	// +optional
	ForceRLS *bool `json:"forceRLS,omitempty"`

	// Privileges declares per-table GRANT statements that should hold
	// against this table. Every entry expands at reconcile time to:
	//
	//   GRANT <Privileges> ON TABLE <Name> TO <ToRole>;
	//
	// Used to heal already-orphaned tables (created before
	// DefaultPrivileges was declared on the parent SchemaDefinition)
	// and to grant non-default privileges to specific roles.
	// DefaultPrivileges in the parent SchemaDefinitionSpec covers the
	// "every new table" case; this field is the per-table override.
	//
	// +optional
	// +kubebuilder:validation:MaxItems=32
	Privileges []DesiredTablePrivilege `json:"privileges,omitempty"`

	// CheckConstraints declares table-level CHECK constraints that must
	// hold for the table. Each entry expands at reconcile time to:
	//
	//   ALTER TABLE <Name> ADD CONSTRAINT <Name> CHECK (<Definition>);
	//
	// Drop is gated by SchemaDefinitionSpec.AllowDestructive — without
	// it, removed entries from this list produce a warning and are not
	// emitted, identical to the column-drop policy. Definition is
	// passed verbatim into the SQL CHECK clause; the SDK does NOT
	// canonicalise expressions, so an exact textual match against the
	// existing pg_constraint definition is required for the differ to
	// recognise an unchanged constraint as already-applied.
	//
	// +optional
	// +kubebuilder:validation:MaxItems=32
	CheckConstraints []DesiredCheckConstraint `json:"checkConstraints,omitempty"`

	// UniqueConstraints declares table-level UNIQUE constraints. Prefer
	// these over a unique entry in Indexes whenever a foreign key might
	// reference the columns: PostgreSQL will not accept a bare unique
	// index as an FK target.
	//
	// +optional
	// +kubebuilder:validation:MaxItems=32
	UniqueConstraints []DesiredUniqueConstraint `json:"uniqueConstraints,omitempty"`

	// PrimaryKeyName names the PRIMARY KEY constraint. Empty lets
	// PostgreSQL derive it, which yields `<table>_pkey`.
	//
	// Set it to reproduce a schema whose primary key was named
	// explicitly — every ORM does this, EF Core emits `PK_<Table>` — so
	// that an adopted schema round-trips under its own name rather than
	// silently acquiring PostgreSQL's default. The name is not merely
	// cosmetic: `ON CONFLICT ON CONSTRAINT` and `ALTER TABLE DROP
	// CONSTRAINT` both address it.
	//
	// Naming the constraint forces the table-level `CONSTRAINT <name>
	// PRIMARY KEY (...)` spelling, since the inline column shorthand has
	// nowhere to carry a name.
	//
	// +optional
	// +kubebuilder:validation:MaxLength=63
	PrimaryKeyName string `json:"primaryKeyName,omitempty"`
}

// DesiredCheckConstraint is one table-level CHECK constraint.
//
// Single-column CHECKs can also be expressed via DesiredColumn.Check
// (when shipped as a future API addition); use this list for
// multi-column predicates and named constraints that integration
// tests assert by name.
type DesiredCheckConstraint struct {
	// Name of the constraint. Must be unique within the table and
	// follow the standard PG identifier rules (snake_case, max 63
	// chars, leading underscore allowed).
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:Pattern=`^[a-z_][a-z0-9_]*$`
	Name string `json:"name"`

	// Definition is the predicate expression to enforce, exactly as
	// it would appear inside the CHECK (...) parentheses. The differ
	// does NOT canonicalise this string before comparing to
	// pg_constraint.consrc — produce it via the same expression
	// printer keystonectl uses to avoid spurious diffs.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=1024
	Definition string `json:"definition"`
}

// DesiredUniqueConstraint declares a table-level UNIQUE constraint.
//
// Distinct from a unique DesiredIndex on purpose. PostgreSQL implements
// a UNIQUE constraint with a unique index, so the two enforce the same
// rule — but only a constraint can be the target of a foreign key
// (`REFERENCES t (col)` requires a PRIMARY KEY or UNIQUE constraint, not
// a bare unique index). Modelling a constraint as an index therefore
// round-trips a schema into one where existing foreign keys can no
// longer be created.
type DesiredUniqueConstraint struct {
	// Name of the constraint. PostgreSQL names the backing index after
	// it, so the name must not collide with an index name either.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=63
	Name string `json:"name"`

	// Columns is the ordered column list the constraint spans. Order is
	// significant: it determines the backing index's column order, and
	// therefore which prefix lookups the index can serve.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:MaxItems=32
	Columns []string `json:"columns"`

	// NullsNotDistinct selects `UNIQUE NULLS NOT DISTINCT`, where two
	// NULLs collide instead of being treated as different values
	// (PostgreSQL 15+).
	//
	// This is a semantic difference, not a tuning knob: under the
	// default NULLS DISTINCT a nullable unique column accepts unlimited
	// NULL rows. Dropping the flag on round-trip would silently widen
	// what the table accepts.
	//
	// +optional
	NullsNotDistinct bool `json:"nullsNotDistinct,omitempty"`
}

// DesiredDefaultPrivilege expresses one `ALTER DEFAULT PRIVILEGES`
// statement that the SD reconciler emits as part of the bundle.
//
// Semantics:
//
//	ALTER DEFAULT PRIVILEGES FOR ROLE <ForRole>
//	  IN SCHEMA <Schema OR sd.targetSchema>
//	  GRANT <Privileges> ON <ObjectType> TO <ToRole>;
//
// Idempotent in PostgreSQL — re-issuing the same grant against the
// same role/schema/object-type is a no-op (pg_default_acl uniqueness).
//
// Practical example for the example-service 2026-05-12 fix:
//
//	defaultPrivileges:
//	  - forRole: keystone_admin
//	    toRole:  example_service_app
//	    objectType: tables
//	    privileges: [SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER]
//	  - forRole: keystone_admin
//	    toRole:  example_service_app
//	    objectType: sequences
//	    privileges: [USAGE, SELECT, UPDATE]
type DesiredDefaultPrivilege struct {
	// ForRole is the PG role whose CREATE actions the grant attaches
	// to. For Keystone-managed schemas this is typically the role the
	// operator runs migrations as — `keystone_admin`. Required.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:Pattern=`^[a-z_][a-z0-9_]*$`
	ForRole string `json:"forRole"`

	// ToRole is the PG role receiving the granted privileges.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:Pattern=`^[a-z_][a-z0-9_]*$`
	ToRole string `json:"toRole"`

	// Schema names the schema the default-privileges apply IN. When
	// empty, defaults to the SchemaDefinition's target schema (i.e.
	// the schema resolved via SchemaRef or SchemaSelector). Use
	// "public" for the public schema.
	//
	// +optional
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:Pattern=`^[a-z_][a-z0-9_]*$`
	Schema string `json:"schema,omitempty"`

	// ObjectType is the PG default-privileges object class. Mirrors
	// the keyword that follows ON in PostgreSQL's
	// `ALTER DEFAULT PRIVILEGES ... ON <ObjectType>` syntax. Common
	// values: tables, sequences, functions, types.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Enum=tables;sequences;functions;types;schemas
	ObjectType string `json:"objectType"`

	// Privileges is the privilege set granted. Validated against the
	// PG privilege keywords valid for the given ObjectType — e.g.
	// `tables` accepts SELECT/INSERT/UPDATE/DELETE/TRUNCATE/REFERENCES
	// /TRIGGER/MAINTAIN; `sequences` accepts USAGE/SELECT/UPDATE.
	// The literal string `ALL` is also accepted (Keystone analyzers
	// surface a warning for the GRANT-ALL footgun via the
	// `no-grant-all` rule.)
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:MaxItems=16
	Privileges []string `json:"privileges"`

	// WithGrantOption mirrors the SQL `WITH GRANT OPTION` clause.
	// When true the receiving role can re-grant the privileges to
	// other roles. Default false.
	//
	// +optional
	WithGrantOption bool `json:"withGrantOption,omitempty"`
}

// DesiredTablePrivilege expresses one per-table GRANT statement.
//
// Semantics:
//
//	GRANT <Privileges> ON TABLE <table> TO <ToRole>;
//
// Used to heal already-orphaned tables that were created before
// DefaultPrivileges was declared on the parent SchemaDefinition, and
// to grant non-default privileges to specific roles. Idempotent in
// PostgreSQL.
type DesiredTablePrivilege struct {
	// ToRole is the PG role receiving the granted privileges.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:Pattern=`^[a-z_][a-z0-9_]*$`
	ToRole string `json:"toRole"`

	// Privileges is the privilege set granted. Same validation as
	// DesiredDefaultPrivilege.Privileges.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:MaxItems=16
	Privileges []string `json:"privileges"`

	// WithGrantOption mirrors the SQL `WITH GRANT OPTION` clause.
	//
	// +optional
	WithGrantOption bool `json:"withGrantOption,omitempty"`
}

// DesiredEnum declares a PostgreSQL enum type.
type DesiredEnum struct {
	// Name is the enum type name.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:Pattern=`^[a-z_][a-z0-9_]*$`
	Name string `json:"name"`

	// Values is the ordered list of enum labels.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:MaxItems=256
	Values []string `json:"values"`
}

// DesiredExtension declares a PostgreSQL extension the schema depends on
// (pgcrypto for gen_random_uuid(), citext, postgis, …).
//
// Extensions are part of the desired state because they are a
// prerequisite for it: a column defaulting to gen_random_uuid() fails to
// create unless pgcrypto exists. Without this the differ cannot tell an
// extension-provided object from drift, and re-creates or drops objects
// the extension owns.
type DesiredExtension struct {
	// Name is the extension name as CREATE EXTENSION spells it.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:Pattern=`^[a-z_][a-z0-9_-]*$`
	Name string `json:"name"`

	// Schema pins the extension to a specific schema. Empty installs it
	// wherever the target's search_path puts it, which is the right
	// default: extensions are commonly shared across schemas, and pinning
	// one to the schema currently being diffed would make the desired
	// state non-portable between environments.
	//
	// +optional
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:Pattern=`^[a-z_][a-z0-9_]*$`
	Schema string `json:"schema,omitempty"`
}

// DesiredSequence declares a PostgreSQL sequence.
type DesiredSequence struct {
	// Name is the sequence name.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:Pattern=`^[a-z_][a-z0-9_]*$`
	Name string `json:"name"`

	// DataType is the sequence's data type (smallint, integer, bigint).
	//
	// +kubebuilder:default="bigint"
	// +kubebuilder:validation:Enum=smallint;integer;bigint
	DataType string `json:"dataType,omitempty"`

	// IncrementBy is the step value.
	//
	// +optional
	// +kubebuilder:default=1
	// +kubebuilder:validation:Minimum=1
	IncrementBy int64 `json:"incrementBy,omitempty"`

	// MinValue is the minimum value. 0 means PG default.
	//
	// +optional
	MinValue int64 `json:"minValue,omitempty"`

	// MaxValue is the maximum value. 0 means PG default.
	//
	// +optional
	MaxValue int64 `json:"maxValue,omitempty"`

	// StartWith is the starting value. 0 means PG default.
	//
	// +optional
	StartWith int64 `json:"startWith,omitempty"`

	// OwnedBy ties the sequence to a column (schema "table.column" format).
	// When the owning column is dropped, the sequence is too.
	//
	// +optional
	// +kubebuilder:validation:MaxLength=127
	OwnedBy string `json:"ownedBy,omitempty"`
}

// DesiredView declares a PostgreSQL view.
type DesiredView struct {
	// Name is the view name.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:Pattern=`^[a-z_][a-z0-9_]*$`
	Name string `json:"name"`

	// Query is the SELECT statement backing the view.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=65536
	Query string `json:"query"`

	// Replace controls CREATE OR REPLACE semantics. When true, the
	// differ always emits CREATE OR REPLACE VIEW regardless of whether
	// the view exists. Default false: only CREATE when absent,
	// otherwise warn if the query changed.
	//
	// +optional
	Replace bool `json:"replace,omitempty"`
}

// DesiredFunction declares a PostgreSQL function or procedure.
type DesiredFunction struct {
	// Name is the function name.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:Pattern=`^[a-z_][a-z0-9_]*$`
	Name string `json:"name"`

	// Args is the argument signature (e.g., "p_id uuid, p_name text").
	// Empty string for zero-argument functions.
	//
	// +optional
	// +kubebuilder:validation:MaxLength=2048
	Args string `json:"args,omitempty"`

	// Returns is the return type (e.g., "void", "TABLE(id uuid, name text)").
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=2048
	Returns string `json:"returns"`

	// Language is the PG language.
	//
	// +kubebuilder:default="plpgsql"
	// +kubebuilder:validation:Enum=plpgsql;sql;c;internal
	Language string `json:"language,omitempty"`

	// Body is the function body (between $$ delimiters).
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=65536
	Body string `json:"body"`

	// Replace controls CREATE OR REPLACE semantics. Default true
	// because functions are safely replaceable.
	//
	// +kubebuilder:default=true
	Replace bool `json:"replace,omitempty"`
}

// DesiredMaterializedView declares a PostgreSQL materialized view.
type DesiredMaterializedView struct {
	// Name is the materialized view name.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:Pattern=`^[a-z_][a-z0-9_]*$`
	Name string `json:"name"`

	// Query is the SELECT statement backing the materialized view.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=65536
	Query string `json:"query"`

	// Indexes on the materialized view (optional, for query performance).
	//
	// +optional
	// +kubebuilder:validation:MaxItems=32
	Indexes []DesiredIndex `json:"indexes,omitempty"`

	// WithData controls whether the view is populated on creation.
	// Default true. Set false for large views where you want to
	// REFRESH MATERIALIZED VIEW CONCURRENTLY on a schedule.
	//
	// +kubebuilder:default=true
	WithData bool `json:"withData,omitempty"`
}

// DesiredPolicy declares a PostgreSQL row-level security policy.
type DesiredPolicy struct {
	// Name is the policy name.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:Pattern=`^[a-z_][a-z0-9_]*$`
	Name string `json:"name"`

	// Table is the table this policy applies to.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:Pattern=`^[a-z_][a-z0-9_]*$`
	Table string `json:"table"`

	// Command is the SQL command the policy applies to.
	//
	// +kubebuilder:default="ALL"
	// +kubebuilder:validation:Enum=ALL;SELECT;INSERT;UPDATE;DELETE
	Command string `json:"command,omitempty"`

	// Permissive controls whether the policy is permissive or
	// restrictive. Default true (PERMISSIVE).
	//
	// +kubebuilder:default=true
	Permissive bool `json:"permissive,omitempty"`

	// Roles is the list of roles the policy applies to.
	// Empty or ["public"] means all roles.
	//
	// +optional
	// +kubebuilder:validation:MaxItems=16
	Roles []string `json:"roles,omitempty"`

	// Using is the USING expression (row visibility filter).
	// Applied to SELECT, UPDATE, DELETE.
	//
	// +optional
	// +kubebuilder:validation:MaxLength=4096
	Using string `json:"using,omitempty"`

	// WithCheck is the WITH CHECK expression (row write filter).
	// Applied to INSERT, UPDATE.
	//
	// +optional
	// +kubebuilder:validation:MaxLength=4096
	WithCheck string `json:"withCheck,omitempty"`
}

// DesiredTrigger declares a PostgreSQL trigger binding.
type DesiredTrigger struct {
	// Name is the trigger name.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:Pattern=`^[a-z_][a-z0-9_]*$`
	Name string `json:"name"`

	// Table is the table the trigger is attached to.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:Pattern=`^[a-z_][a-z0-9_]*$`
	Table string `json:"table"`

	// Timing is BEFORE or AFTER.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Enum=BEFORE;AFTER;INSTEAD OF
	Timing string `json:"timing"`

	// Events is the list of events that fire the trigger.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:MaxItems=4
	Events []string `json:"events"`

	// ForEachRow controls whether the trigger fires per row or per
	// statement. Default true (FOR EACH ROW).
	//
	// +kubebuilder:default=true
	ForEachRow bool `json:"forEachRow,omitempty"`

	// Function is the trigger function name (must exist in spec.functions
	// or already in the database). The function must return TRIGGER.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=63
	Function string `json:"function"`

	// When is an optional conditional expression. The trigger only
	// fires when this evaluates to true.
	//
	// +optional
	// +kubebuilder:validation:MaxLength=4096
	When string `json:"when,omitempty"`
}

// MixedVersionPolicy controls how the SchemaDefinition reconciler
// behaves when SchemaSelector matches multiple DatabaseSchemas whose
// observed shapes diverge from each other (i.e. some tenants are
// ahead of others).
//
// Refuse (default) is the audit-grade choice: surface the drifted
// schemas in Status.DriftedSchemas and emit no bundle until either
// the schemas converge or the operator explicitly overrides via
// MostBehindWins. No silent papering-over of tenant divergence.
//
// MostBehindWins relaxes the gate: the reconciler picks the schema
// that is farthest from desired, emits a bundle whose SQL brings it
// to desired, and lets the runner's idempotent UPSERT semantics
// no-op ahead-of-target tenants. Use only when fan-out drift is an
// expected steady state (e.g. canary roll-out across tiers).
//
// +kubebuilder:validation:Enum=Refuse;MostBehindWins
type MixedVersionPolicy string

const (
	// MixedVersionPolicyRefuse halts the reconciler when fanned-out
	// DatabaseSchemas diverge. Default.
	MixedVersionPolicyRefuse MixedVersionPolicy = "Refuse"
	// MixedVersionPolicyMostBehindWins emits a bundle keyed off the
	// most-behind schema; idempotent SQL handles ahead-tenants.
	MixedVersionPolicyMostBehindWins MixedVersionPolicy = "MostBehindWins"
)

// SchemaDefinitionSpec is the declarative desired-state for one schema
// or for a label-selected fan-out of schemas.
//
// Exactly one of SchemaRef (singular) and SchemaSelector (fan-out)
// must be set. Mixing both is rejected by admission. SchemaRef stays
// the default for single-tenant definitions; SchemaSelector enables
// one SchemaDefinition to drive every DatabaseSchema in a tenant pool
// (the realm-DB pattern in example-service, business-module DBs in example-suite,
// etc.) without per-tenant CR boilerplate.
//
// +kubebuilder:validation:XValidation:rule="(has(self.schemaRef) && self.schemaRef != '') != (has(self.schemaSelector) && self.schemaSelector != null)",message="exactly one of schemaRef or schemaSelector must be set"
type SchemaDefinitionSpec struct {
	// SchemaRef is the DatabaseSchema CR this definition applies to
	// (same namespace). Mutually exclusive with SchemaSelector.
	//
	// +optional
	// +kubebuilder:validation:MaxLength=253
	// +kubebuilder:validation:Pattern=`^[a-z0-9]([-a-z0-9]*[a-z0-9])?$`
	SchemaRef string `json:"schemaRef,omitempty"`

	// SchemaSelector matches every DatabaseSchema in the same namespace
	// whose labels satisfy the selector. The reconciler resolves all
	// matched schemas, computes a per-schema diff, and (subject to
	// MixedVersionPolicy) emits one MigrationBundle whose
	// schemaSelector mirrors this one — the bundle's existing fan-out
	// at apply time then runs against every matched schema.
	//
	// An empty selector ({}) matches everything in-namespace and is
	// rejected by admission to prevent foot-guns; specify at least one
	// matchLabels entry. Mutually exclusive with SchemaRef.
	//
	// +optional
	SchemaSelector *metav1.LabelSelector `json:"schemaSelector,omitempty"`

	// MixedVersionPolicy governs reconciler behaviour when
	// SchemaSelector matches multiple schemas whose observed shapes
	// diverge. Ignored when SchemaRef (singular) is used.
	//
	// +optional
	// +kubebuilder:default="Refuse"
	MixedVersionPolicy MixedVersionPolicy `json:"mixedVersionPolicy,omitempty"`

	// Tables is the ordered list of desired tables.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:MaxItems=1024
	Tables []DesiredTable `json:"tables"`

	// Enums are PostgreSQL enum types. Created before tables that
	// reference them. Drop requires AllowDestructive.
	//
	// +optional
	// +kubebuilder:validation:MaxItems=256
	Enums []DesiredEnum `json:"enums,omitempty"`

	// Extensions are PostgreSQL extensions the schema depends on.
	// Created before everything else, since types and default
	// expressions can come from them.
	//
	// +optional
	// +kubebuilder:validation:MaxItems=64
	Extensions []DesiredExtension `json:"extensions,omitempty"`

	// Sequences are PostgreSQL sequences. Created before tables that
	// use them as DEFAULT values.
	//
	// +optional
	// +kubebuilder:validation:MaxItems=256
	Sequences []DesiredSequence `json:"sequences,omitempty"`

	// Views are PostgreSQL views. Created after all referenced tables.
	//
	// +optional
	// +kubebuilder:validation:MaxItems=256
	Views []DesiredView `json:"views,omitempty"`

	// Functions are PostgreSQL functions/procedures. Created after all
	// referenced types and tables.
	//
	// +optional
	// +kubebuilder:validation:MaxItems=256
	Functions []DesiredFunction `json:"functions,omitempty"`

	// MaterializedViews are PostgreSQL materialized views. Created
	// after all referenced tables. Support indexes for query perf.
	//
	// +optional
	// +kubebuilder:validation:MaxItems=128
	MaterializedViews []DesiredMaterializedView `json:"materializedViews,omitempty"`

	// Policies are PostgreSQL row-level security policies. Requires
	// enableRLS=true on the target table.
	//
	// +optional
	// +kubebuilder:validation:MaxItems=256
	Policies []DesiredPolicy `json:"policies,omitempty"`

	// Triggers are PostgreSQL trigger bindings. The referenced
	// function must exist in spec.functions or already in the DB.
	//
	// +optional
	// +kubebuilder:validation:MaxItems=256
	Triggers []DesiredTrigger `json:"triggers,omitempty"`

	// AllowDestructive gates whether the differ may emit
	// DROP TABLE / DROP COLUMN operations. Default false: the
	// SchemaDefinitionReconciler refuses to plan destructive changes
	// silently. Operators flip this on a per-SchemaDefinition basis
	// when they've reviewed the diff and decided the drop is safe.
	//
	// +kubebuilder:default=false
	AllowDestructive bool `json:"allowDestructive,omitempty"`

	// DefaultPrivileges declares per-role `ALTER DEFAULT PRIVILEGES`
	// that should hold against this schema. Every entry expands at
	// reconcile time to:
	//
	//   ALTER DEFAULT PRIVILEGES FOR ROLE <ForRole>
	//     IN SCHEMA <Schema OR sd.targetSchema>
	//     GRANT <Privileges> ON <ObjectType> TO <ToRole>;
	//
	// Why this exists (gap surfaced 2026-05-12 on example-service migration
	// 234): the operator-emitted bundles run CREATE TABLE as the
	// keystone_admin role. Pre-Keystone default-privileges were set
	// for the `postgres` role, so any keystone_admin-created table
	// silently dropped out of the example_service_app grant chain. The
	// BackchannelLogoutDrainer spammed SQLSTATE 42501 every 5s until
	// a hand-authored migration bundle re-pointed ALTER DEFAULT
	// PRIVILEGES at keystone_admin. With DefaultPrivileges declared
	// here, that recovery is no longer hand-authored — the SD
	// reconciler emits the ALTER DEFAULT PRIVILEGES statement as part
	// of the bundle so every future keystone_admin-created table
	// inherits the grant chain automatically.
	//
	// +optional
	// +kubebuilder:validation:MaxItems=64
	DefaultPrivileges []DesiredDefaultPrivilege `json:"defaultPrivileges,omitempty"`

	// ApplyStrategy selects how the generated MigrationBundle is
	// written: "versioned" (raw ALTER statements) or
	// "pgroll-expand-contract" (zero-downtime for drop/rename/alter).
	// Default "versioned" for greenfield schemas where locks are OK.
	//
	// +kubebuilder:default="versioned"
	// +kubebuilder:validation:Enum=versioned;pgroll-expand-contract
	ApplyStrategy string `json:"applyStrategy,omitempty"`

	// PolicyRef is the SchemaPolicy the reconciler stamps onto the
	// auto-generated MigrationBundle. When empty, the default
	// "production-safety" policy is applied — this matches the value
	// used by every hand-authored bundle in the GitOps repository
	// and ensures the downstream MigrationBundle controller has a
	// policy to look up (without a policyRef, the bundle pipeline
	// stalls before creating a MigrationPlan).
	//
	// +optional
	// +kubebuilder:validation:MaxLength=253
	// +kubebuilder:validation:Pattern=`^[a-z0-9]([-a-z0-9]*[a-z0-9])?$`
	PolicyRef string `json:"policyRef,omitempty"`

	// Cleanup configures the per-SD TTL policy applied to terminal
	// MigrationBundle and MigrationExecution CRs owned by this
	// SchemaDefinition. Without this controller running, terminal CRs
	// accumulate without bound — the 2026-05-08 incident demonstrated
	// the failure mode at 182 954 AuditEntries / 4.7 GB etcd / 17 h
	// apiserver outage. (AuditEntry has its own off-cluster archive
	// path under spec.archive on AuditLog; this Cleanup field covers
	// the operator's own transient bundles + executions whose payload
	// stays on-cluster.)
	//
	// Nil = use the operator-wide defaults (24 h success / 7 d
	// failure). Non-terminal CRs (Pending / Running / Expanding /
	// Aborting / RollingBack) are NEVER deleted regardless of age —
	// the controller only acts on Succeeded / Failed / Aborted /
	// RolledBack / RollbackFailed phases. The latest succeeded
	// MigrationBundle and the latest succeeded MigrationExecution per
	// (SD, schema) tuple are always retained so the SD reconciler can
	// re-emit decisions and operators can read "what last shipped".
	//
	// Behind the operator-level --enable-cr-ttl feature flag (default
	// off for first release) so existing clusters opt in deliberately.
	//
	// +optional
	Cleanup *CleanupPolicy `json:"cleanup,omitempty"`
}

// CleanupPolicy is the per-SchemaDefinition retention configuration for
// terminal MigrationBundle + MigrationExecution CRs. Mirrors Argo
// Workflows' spec.ttlStrategy.{secondsAfterSuccess, secondsAfterFailure}
// shape but uses metav1.Duration so operators write ergonomic strings
// like "24h" and "7d" rather than raw integer seconds.
//
// Both fields are optional — leaving either unset falls through to the
// operator-wide defaults (RetainSuccessFor=24 h, RetainFailureFor=7 d).
// A zero Duration is rejected: it would mean "delete immediately on
// terminal phase observation", which removes the operator's window to
// emit metrics and Events about the success/failure outcome. Negative
// durations are rejected at admission via the Minimum kubebuilder
// marker.
type CleanupPolicy struct {
	// RetainSuccessFor is how long to keep a Succeeded MigrationBundle
	// or MigrationExecution before garbage collection. The latest
	// Succeeded CR per kind is ALWAYS retained regardless of age — the
	// SD reconciler reads it for re-emit decisions and the operator
	// uses it to answer "what last shipped". This field controls the
	// retention window for older Succeeded siblings, where one
	// generation per fan-out tenant accumulates at every reconcile.
	//
	// Operators wanting longer post-mortem windows on success can bump
	// this to 7d or more. The 2026-05-08 outage post-mortem suggests
	// 24 h is the right default: long enough for humans to see the
	// rollout in `kubectl get mb -A`, short enough that a 100-tenant
	// fan-out reconciling every 30 min doesn't accumulate beyond
	// O(thousands).
	//
	// Empty / nil = use the operator-wide default (24h).
	//
	// +optional
	RetainSuccessFor *metav1.Duration `json:"retainSuccessFor,omitempty"`

	// RetainFailureFor is how long to keep a Failed / Aborted /
	// RollbackFailed MigrationBundle or MigrationExecution before
	// garbage collection. Failures need a longer post-mortem window
	// than successes — the on-call engineer who picks up the page on
	// Friday afternoon needs the failure CR to still exist Monday
	// morning. 7d default matches the standard "two weekend windows"
	// rule.
	//
	// Empty / nil = use the operator-wide default (7d).
	//
	// +optional
	RetainFailureFor *metav1.Duration `json:"retainFailureFor,omitempty"`
}

// SchemaDefinitionStatus reports the observed diff + auto-generated
// MigrationBundle reference.
type SchemaDefinitionStatus struct {
	// ObservedGeneration is the .metadata.generation last reconciled.
	//
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`

	// Conditions:
	//   Ready           — schema matches desired state
	//   Inspected       — live inspection completed successfully
	//   DiffComputed    — differ produced an operation plan (True with
	//                     reason=NoDrift means the plan was empty)
	//   BundleGenerated — a MigrationBundle was emitted to Apply the
	//                     diff; tracks CurrentBundleRef, so False
	//                     whenever that field is empty
	//
	// The last three are pipeline stages, re-stated on every terminal
	// path rather than latched, so all four always describe the same
	// reconcile. See ConditionTypeInspected and friends.
	//
	// +optional
	// +patchMergeKey=type
	// +patchStrategy=merge
	// +listType=map
	// +listMapKey=type
	Conditions []metav1.Condition `json:"conditions,omitempty" patchStrategy:"merge" patchMergeKey:"type"`

	// CurrentBundleRef is the auto-generated MigrationBundle that's
	// currently applying the diff. Empty when the schema matches
	// desired state (Ready=True).
	//
	// +optional
	// +kubebuilder:validation:MaxLength=253
	CurrentBundleRef string `json:"currentBundleRef,omitempty"`

	// PendingOperations counts the diff size from the last reconcile.
	// 0 means the schema is at desired state. When SchemaSelector
	// fan-out is used this reflects the size of the emitted bundle's
	// op set (i.e. the most-behind schema's diff under MostBehindWins
	// policy, or the lockstep diff under Refuse with all schemas in
	// agreement).
	//
	// +optional
	PendingOperations int32 `json:"pendingOperations,omitempty"`

	// LastDiffTime is when the differ last ran.
	//
	// +optional
	LastDiffTime *metav1.Time `json:"lastDiffTime,omitempty"`

	// MatchedSchemas is the count of DatabaseSchemas the reconciler
	// resolved on the last pass. 1 for SchemaRef, N for SchemaSelector.
	// Surfaces fan-out width on `kubectl get sd`.
	//
	// +optional
	MatchedSchemas int32 `json:"matchedSchemas,omitempty"`

	// Fingerprint is a deterministic hash of the SD's desired-state
	// spec (tables + columns + indexes + functions + ... — same
	// inputs the differ consumes). Recomputed on every reconcile;
	// changes whenever the operator edits the spec. The SD reconciler
	// stamps this on every emitted MigrationBundle as the annotation
	// `keystone.hexxlock.io/sd-fingerprint`; the bundle runner copies
	// it onto DatabaseSchema.Status.LastAppliedFingerprint when a
	// MigrationExecution succeeds for that schema.
	//
	// SDK consumers (keystone-sdk/go/keystone.WaitSchemaFingerprint) compare
	// this against per-schema LastAppliedFingerprint to verify
	// convergence in an identity-based, race-free way.
	//
	// Empty when the spec has never been hashed (very first reconcile
	// of a freshly-applied SD).
	//
	// +optional
	// +kubebuilder:validation:MaxLength=64
	Fingerprint string `json:"fingerprint,omitempty"`

	// DriftedSchemas lists DatabaseSchemas whose observed shapes
	// diverge from the lockstep set when SchemaSelector + MixedVersion
	// Policy=Refuse is in effect. Empty under MostBehindWins (the
	// reconciler proceeds rather than recording divergence) and empty
	// under SchemaRef (no fan-out, no divergence to surface).
	//
	// +optional
	// +listType=atomic
	// +kubebuilder:validation:MaxItems=1024
	DriftedSchemas []DriftedSchema `json:"driftedSchemas,omitempty"`
}

// DriftedSchema records one fanned-out DatabaseSchema that diverges
// from the lockstep set under MixedVersionPolicy=Refuse.
type DriftedSchema struct {
	// SchemaRef is the DatabaseSchema's metadata.name.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=253
	SchemaRef string `json:"schemaRef"`

	// PendingOperations is the diff size for this individual schema
	// against the SchemaDefinition's desired state. The schema with
	// the largest PendingOperations is the most-behind candidate.
	//
	// +kubebuilder:validation:Required
	PendingOperations int32 `json:"pendingOperations"`

	// LastInspectedAt is when the reconciler last inspected this
	// schema's live shape.
	//
	// +optional
	LastInspectedAt *metav1.Time `json:"lastInspectedAt,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:resource:scope=Namespaced,shortName=sd;schemadef
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="SchemaRef",type="string",JSONPath=".spec.schemaRef"
// +kubebuilder:printcolumn:name="Tables",type="integer",JSONPath=".spec.tables[*]"
// +kubebuilder:printcolumn:name="Pending",type="integer",JSONPath=".status.pendingOperations"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type==\"Ready\")].status"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"

// SchemaDefinition declares the desired shape of a DatabaseSchema. The
// controller diffs live state against this spec and auto-generates a
// MigrationBundle with the necessary DDL. Atlas-parity DX for
// declarative schema authoring.
//
// Phase 10.1 ships the CRD only. Phase 10.2 ships the differ.
// Phase 10.3 ships the reconciler.
type SchemaDefinition struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   SchemaDefinitionSpec   `json:"spec,omitempty"`
	Status SchemaDefinitionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SchemaDefinitionList is the list wrapper required by client-go.
type SchemaDefinitionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SchemaDefinition `json:"items"`
}

func init() {
	SchemeBuilder.Register(&SchemaDefinition{}, &SchemaDefinitionList{})
}
