// SPDX-License-Identifier: Apache-2.0

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ExecutionPhase is the coarse lifecycle for a MigrationExecution.
//
// +kubebuilder:validation:Enum=Pending;Running;Expanding;Expanded;Contracting;Aborting;RollingBack;Succeeded;Failed;Aborted;RolledBack;RollbackFailed
type ExecutionPhase string

const (
	ExecutionPhasePending     ExecutionPhase = "Pending"
	ExecutionPhaseRunning     ExecutionPhase = "Running"
	ExecutionPhaseExpanding   ExecutionPhase = "Expanding"
	ExecutionPhaseExpanded    ExecutionPhase = "Expanded"
	ExecutionPhaseContracting ExecutionPhase = "Contracting"
	// ExecutionPhaseAborting is transient — the controller is running
	// per-op abort handlers to roll back an in-flight Expand. On success
	// the phase advances to Aborted; on failure it sticks at Aborting
	// and the reconcile retries.
	ExecutionPhaseAborting  ExecutionPhase = "Aborting"
	ExecutionPhaseSucceeded ExecutionPhase = "Succeeded"
	ExecutionPhaseFailed    ExecutionPhase = "Failed"
	ExecutionPhaseAborted   ExecutionPhase = "Aborted"

	// ExecutionPhaseRollingBack is entered when autoRollback=true and
	// a down source exists. The controller resolves the down source
	// and applies it to undo the forward migration.
	ExecutionPhaseRollingBack ExecutionPhase = "RollingBack"

	// ExecutionPhaseRolledBack is the terminal state after a successful
	// rollback. The down source was applied and the schema_migrations
	// entry was removed.
	ExecutionPhaseRolledBack ExecutionPhase = "RolledBack"

	// ExecutionPhaseRollbackFailed is the terminal state when the
	// rollback itself fails. Manual intervention required.
	ExecutionPhaseRollbackFailed ExecutionPhase = "RollbackFailed"
)

// AnnotationCompleteContraction is the explicit operator opt-in for the
// Contract phase to run after Expanded. Set the annotation to "true" on
// the MigrationExecution once apps are confirmed deployed against the
// expanded schema. Without it, executions stay in Expanded forever.
const AnnotationCompleteContraction = "keystone.hexxlock.io/complete"

// AnnotationAbortMigration signals the controller to roll back an
// in-flight pgroll execution. Setting the annotation to "true" on a
// MigrationExecution whose phase is Pending / Running / Expanding /
// Expanded transitions the execution into Aborting, where the engine
// runs per-operation abort handlers (drop shadow columns, drop
// triggers, drop NOT VALID constraints) in reverse operation order
// until the schema is restored to pre-Expand state. Final phase is
// Aborted (terminal, same retention as Succeeded / Failed).
//
// Abort on Contracting is best-effort: once Contract starts dropping
// real columns the data is gone and the abort handler cannot restore
// it. The controller treats Contracting aborts as hard failures and
// records the diagnostic in the execution's Conditions.
const AnnotationAbortMigration = "keystone.hexxlock.io/abort"

// AppliedStatement records what actually ran on the target schema.
type AppliedStatement struct {
	// File the statement was sourced from.
	File string `json:"file"`

	// Index within File.
	Index int32 `json:"index"`

	// DurationMS is the wall-clock duration in milliseconds.
	//
	// +kubebuilder:validation:Minimum=0
	DurationMS int64 `json:"durationMS"`

	// RowsAffected is the PostgreSQL command tag's RowsAffected. -1 for
	// statements that don't return one (most DDL).
	//
	// +kubebuilder:validation:Minimum=-1
	RowsAffected int64 `json:"rowsAffected"`
}

// MigrationExecutionSpec is the immutable definition of one run.
// Generated by the MigrationController; users do NOT author executions
// directly.
type MigrationExecutionSpec struct {
	// PlanRef is the MigrationPlan this execution is realising.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=253
	PlanRef string `json:"planRef"`

	// BundleRef + BundleVersion duplicate spec from the plan for
	// audit clarity (Plans get garbage-collected; Executions are kept
	// for the audit retention window).
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=253
	BundleRef string `json:"bundleRef"`

	// MaxLength 253 mirrors MigrationBundle.spec.version + MigrationPlan
	// .spec.bundleVersion (kept symmetric to accommodate the content-
	// addressed naming `<sd.Name>-declarative-<contentHash>` introduced
	// in 372de32). 64 char limit on this field would silently reject
	// Executions for Plans/Bundles that the upstream CRDs accept.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=253
	BundleVersion string `json:"bundleVersion"`

	// SchemaRef is the DatabaseSchema being mutated.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=253
	SchemaRef string `json:"schemaRef"`

	// ContentHash is the SHA-256 of the SQL content the plan was
	// generated from. The runner re-resolves the source and refuses
	// to apply if the hash drifted (paranoia gate against
	// time-of-check / time-of-use bugs).
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=64
	ContentHash string `json:"contentHash"`

	// ExecutionMode is frozen from the bundle at fan-out time, like
	// ContentHash, so a later bundle mutation cannot change what an
	// in-flight execution does. RecordOnly executions upsert the
	// tracking-table row without running any SQL (adoption baseline,
	// ADR 0027). Empty is equivalent to Apply (pre-ADR-0027 objects).
	//
	// +kubebuilder:default="Apply"
	// +optional
	ExecutionMode ExecutionMode `json:"executionMode,omitempty"`
}

// MigrationExecutionStatus reports the run.
type MigrationExecutionStatus struct {
	// ObservedGeneration is the .metadata.generation last reconciled.
	//
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`

	// Phase is the coarse lifecycle.
	//
	// +optional
	Phase ExecutionPhase `json:"phase,omitempty"`

	// Conditions:
	//   Started   — controller picked it up and acquired the schema lock.
	//   Applied   — every statement ran successfully and was committed.
	//   Succeeded — Applied + version recorded in schema_migrations table.
	//   Failed    — at least one statement errored; transaction rolled back.
	//
	// +optional
	// +patchMergeKey=type
	// +patchStrategy=merge
	// +listType=map
	// +listMapKey=type
	Conditions []metav1.Condition `json:"conditions,omitempty" patchStrategy:"merge" patchMergeKey:"type"`

	// StartTime is when the runner began the apply transaction.
	//
	// +optional
	StartTime *metav1.Time `json:"startTime,omitempty"`

	// CompletionTime is when the runner exited (success or failure).
	//
	// +optional
	CompletionTime *metav1.Time `json:"completionTime,omitempty"`

	// Applied lists what ran. Empty for failed-before-first-statement.
	//
	// +optional
	// +kubebuilder:validation:MaxItems=2048
	Applied []AppliedStatement `json:"applied,omitempty"`

	// FailedAtFile + FailedAtIndex pinpoint the first failing statement.
	//
	// +optional
	FailedAtFile string `json:"failedAtFile,omitempty"`

	// +optional
	// +kubebuilder:validation:Minimum=0
	FailedAtIndex int32 `json:"failedAtIndex,omitempty"`

	// FailureMessage is the PostgreSQL error verbatim. Truncated to
	// 4 KiB to keep the CR manageable.
	//
	// +optional
	// +kubebuilder:validation:MaxLength=4096
	FailureMessage string `json:"failureMessage,omitempty"`

	// ReversalStatements is the list of SQL statements that would undo
	// the forward migration. Populated by the declarative differ
	// (Plan.ReverseStatements) or from a resolved down source. Index-
	// aligned with the forward statements when generated by the differ.
	// Empty string entries indicate non-reversible operations (data
	// loss from DROP COLUMN, etc.). Used for emergency manual rollback
	// or by the auto-rollback controller.
	//
	// +optional
	// +kubebuilder:validation:MaxItems=2048
	ReversalStatements []string `json:"reversalStatements,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:resource:scope=Namespaced,shortName=me;exec
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Bundle",type="string",JSONPath=".spec.bundleRef"
// +kubebuilder:printcolumn:name="Version",type="string",JSONPath=".spec.bundleVersion"
// +kubebuilder:printcolumn:name="Schema",type="string",JSONPath=".spec.schemaRef"
// +kubebuilder:printcolumn:name="Phase",type="string",JSONPath=".status.phase"
// +kubebuilder:printcolumn:name="Started",type="date",JSONPath=".status.startTime"
// +kubebuilder:printcolumn:name="Done",type="date",JSONPath=".status.completionTime"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"

// MigrationExecution is the per-target run. Created by the
// MigrationController from a MigrationPlan that passed admission.
type MigrationExecution struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   MigrationExecutionSpec   `json:"spec,omitempty"`
	Status MigrationExecutionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MigrationExecutionList is the list wrapper required by client-go.
type MigrationExecutionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MigrationExecution `json:"items"`
}

func init() {
	SchemeBuilder.Register(&MigrationExecution{}, &MigrationExecutionList{})
}
