// SPDX-License-Identifier: Apache-2.0

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DriftSeverity grades a DriftReport for triage routing.
//
// +kubebuilder:validation:Enum=info;warning;critical
type DriftSeverity string

const (
	// DriftSeverityInfo — schema fingerprint changed but no objects
	// were dropped. Typical of operator-applied migrations the
	// MigrationController is about to record.
	DriftSeverityInfo DriftSeverity = "info"

	// DriftSeverityWarning — objects added, modified, or columns
	// re-typed without a corresponding MigrationExecution. Most
	// real drift sits here.
	DriftSeverityWarning DriftSeverity = "warning"

	// DriftSeverityCritical — objects DROPPED. Highest priority;
	// pages oncall.
	DriftSeverityCritical DriftSeverity = "critical"
)

// DriftReportSpec is generated by the DriftController; users do NOT
// author DriftReports directly.
type DriftReportSpec struct {
	// DatabaseSchemaRef is the namespaced name of the DatabaseSchema
	// the report is about. Same namespace as the report.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=253
	DatabaseSchemaRef string `json:"databaseSchemaRef"`

	// LogicalDatabaseRef is duplicated from the schema so a single
	// `kubectl get driftreports -o wide` is useful without joining
	// across CR types.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=253
	LogicalDatabaseRef string `json:"logicalDatabaseRef"`

	// ProviderRef is duplicated from the LogicalDatabase for the same
	// reason.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=253
	ProviderRef string `json:"providerRef"`
}

// DriftFinding describes one delta between the recorded baseline and the
// observed live schema. The DriftController fills the slice when it
// detects drift; an empty slice means "drift detected by hash but
// no per-object diff was computed yet" (Phase 5.1 will populate it).
type DriftFinding struct {
	// Kind classifies the finding.
	//
	// The RLS* and Policy* kinds describe a change in ENFORCEMENT rather
	// than in shape. They are graded Critical when enforcement is lost
	// (see drift.Severity) because, unlike a dropped column, nothing about
	// the schema's shape looks wrong afterwards.
	//
	// This enum gates what the controller may write: an unlisted kind fails
	// apiserver validation and takes the entire DriftReport patch with it,
	// so it must stay in step with the kinds drift.Diff emits.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Enum=TableAdded;TableDropped;ColumnAdded;ColumnDropped;ColumnChanged;IndexAdded;IndexDropped;ConstraintAdded;ConstraintDropped;RLSEnabled;RLSDisabled;RLSForced;RLSUnforced;PolicyAdded;PolicyDropped;PolicyChanged;Other
	Kind string `json:"kind"`

	// Object is the qualified PG object name (e.g. "crm.leads.score").
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=512
	Object string `json:"object"`

	// Description is human-readable detail.
	//
	// +kubebuilder:validation:MaxLength=2048
	Description string `json:"description,omitempty"`
}

// DriftReportStatus reports the live observation.
type DriftReportStatus struct {
	// ObservedGeneration is the .metadata.generation last reconciled.
	//
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`

	// Severity grades the finding for routing.
	//
	// +optional
	Severity DriftSeverity `json:"severity,omitempty"`

	// Conditions:
	//   Detected   — controller observed a hash mismatch
	//   Acknowledged — operator marked the drift as accepted (Phase 5.1)
	//   Resolved   — drift was reconciled (live matches baseline again)
	//
	// +optional
	// +patchMergeKey=type
	// +patchStrategy=merge
	// +listType=map
	// +listMapKey=type
	Conditions []metav1.Condition `json:"conditions,omitempty" patchStrategy:"merge" patchMergeKey:"type"`

	// DetectedAt is when the controller first observed the drift.
	//
	// +optional
	DetectedAt *metav1.Time `json:"detectedAt,omitempty"`

	// LastObservedAt is the most recent inspection that confirmed the
	// drift still exists.
	//
	// +optional
	LastObservedAt *metav1.Time `json:"lastObservedAt,omitempty"`

	// ExpectedHash is the baseline hash recorded after the last
	// successful migration (or operator acceptance).
	//
	// +optional
	// +kubebuilder:validation:MaxLength=64
	ExpectedHash string `json:"expectedHash,omitempty"`

	// ObservedHash is the hash of the live schema at LastObservedAt.
	//
	// +optional
	// +kubebuilder:validation:MaxLength=64
	ObservedHash string `json:"observedHash,omitempty"`

	// Findings holds per-object deltas. Empty in Phase 5 (hash-only
	// detection); populated in Phase 5.1 when the inspector grows a
	// structural diff implementation.
	//
	// +optional
	// +kubebuilder:validation:MaxItems=128
	Findings []DriftFinding `json:"findings,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:resource:scope=Namespaced,shortName=dr;drift
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Schema",type="string",JSONPath=".spec.databaseSchemaRef"
// +kubebuilder:printcolumn:name="Database",type="string",JSONPath=".spec.logicalDatabaseRef"
// +kubebuilder:printcolumn:name="Severity",type="string",JSONPath=".status.severity"
// +kubebuilder:printcolumn:name="Detected",type="date",JSONPath=".status.detectedAt"
// +kubebuilder:printcolumn:name="LastSeen",type="date",JSONPath=".status.lastObservedAt"
// +kubebuilder:printcolumn:name="Findings",type="integer",JSONPath=".status.findings[*]"

// DriftReport records a divergence between a DatabaseSchema's recorded
// baseline and the live PostgreSQL state. Created by the DriftController;
// users acknowledge or resolve by deleting / labelling.
type DriftReport struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   DriftReportSpec   `json:"spec,omitempty"`
	Status DriftReportStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DriftReportList is the list wrapper required by client-go.
type DriftReportList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DriftReport `json:"items"`
}

func init() {
	SchemeBuilder.Register(&DriftReport{}, &DriftReportList{})
}
