// SPDX-License-Identifier: AGPL-3.0-or-later

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// LintFinding is a single squawk/conftest finding produced during the
// plan phase.
type LintFinding struct {
	// Severity matches LintLevel: error | warning | notice.
	//
	// +kubebuilder:validation:Required
	Severity LintLevel `json:"severity"`

	// Rule is the linter's rule identifier (e.g. squawk's
	// "adding-required-field" or conftest's "deny-truncate").
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=128
	Rule string `json:"rule"`

	// File is the SQL filename within the source where the finding fired.
	//
	// +kubebuilder:validation:MaxLength=253
	File string `json:"file,omitempty"`

	// Line is the 1-indexed line in the source file. 0 if not applicable.
	//
	// +optional
	// +kubebuilder:validation:Minimum=0
	Line int32 `json:"line,omitempty"`

	// Message is a human-readable description.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=4096
	Message string `json:"message"`
}

// PlannedStatement is one DDL statement the controller intends to execute,
// surfaced for review before MigrationExecutions are created.
type PlannedStatement struct {
	// File is the source filename the statement came from.
	File string `json:"file"`

	// Index is the 1-indexed statement number within File.
	//
	// +kubebuilder:validation:Minimum=1
	Index int32 `json:"index"`

	// SQL is the rendered statement text (truncated to 4 KiB to keep
	// the CR size manageable; full SQL is in the source ConfigMap).
	//
	// +kubebuilder:validation:MaxLength=4096
	SQL string `json:"sql"`
}

// MigrationPlanSpec is generated by the MigrationController; users do
// NOT author plans directly. Spec is intentionally narrow because a plan
// is a snapshot of a (bundle, schema) pair at a point in time.
type MigrationPlanSpec struct {
	// BundleRef is the MigrationBundle this plan was generated from.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=253
	BundleRef string `json:"bundleRef"`

	// BundleVersion freezes the bundle version at the moment the plan
	// was generated. If the bundle changes after the plan is created,
	// the plan stays accurate to its snapshot — a new plan is generated
	// for the new version.
	//
	// MaxLength 253 mirrors MigrationBundle.spec.version (bumped in
	// keystone!109) — bundleVersion must accommodate the content-
	// addressed naming `<sd.Name>-declarative-<contentHash>` introduced
	// in 372de32. Asymmetric limits between Bundle.spec.version and
	// Plan.spec.bundleVersion would silently reject Plans for SDs
	// whose names + hash combo exceed 64 chars even though the upstream
	// Bundle was accepted.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=253
	BundleVersion string `json:"bundleVersion"`

	// SchemaRef is the DatabaseSchema this plan targets.
	//
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MaxLength=253
	SchemaRef string `json:"schemaRef"`

	// Statements is the ordered list of DDL the controller intends to
	// run. Truncated per-statement to 4 KiB; for review of full SQL,
	// inspect the source ConfigMap referenced by the bundle.
	//
	// +kubebuilder:validation:MaxItems=2048
	Statements []PlannedStatement `json:"statements,omitempty"`

	// Findings holds lint output. The MigrationController refuses to
	// graduate the plan into a MigrationExecution if any finding has
	// severity >= the matched SchemaPolicy's MinLintLevel.
	//
	// +optional
	// +kubebuilder:validation:MaxItems=512
	Findings []LintFinding `json:"findings,omitempty"`

	// Approved is the explicit Plan-Gate-Apply gate. The
	// MigrationPlanReconciler sets this to true automatically when the
	// matched SchemaPolicies resolve to approvalMode=Auto (the default
	// for backward compatibility); in Manual mode, a human or CI
	// principal flips it after reviewing spec.statements. The
	// MigrationExecution controller refuses to apply SQL until this
	// field is true.
	//
	// Default false so new plans stop at the gate unless a policy
	// explicitly opts into auto-approval. Existing deployments
	// without a SchemaPolicy declaring planApproval fall back to
	// Auto — matches pre-A4 behavior.
	//
	// +kubebuilder:default=false
	Approved bool `json:"approved,omitempty"`
}

// PlanApprovalMode is the effective approval mode resolved from the
// matched SchemaPolicies. Stored in MigrationPlanStatus for
// observability; see SchemaPolicy.Spec.PlanApproval for the source
// field.
//
// +kubebuilder:validation:Enum=Auto;Manual
type PlanApprovalMode string

const (
	// PlanApprovalAuto auto-flips spec.approved=true when the plan is
	// created (and lint passes). The controller bumps spec.approved
	// itself; operators don't see a pause.
	PlanApprovalAuto PlanApprovalMode = "Auto"

	// PlanApprovalManual leaves spec.approved=false on plan creation.
	// A human or CI principal must explicitly patch the plan
	// (kubectl patch, keystonectl plan approve, GitOps) before
	// executions fire.
	PlanApprovalManual PlanApprovalMode = "Manual"
)

// MigrationPlanStatus reports whether the plan was approved and what
// happened next.
type MigrationPlanStatus struct {
	// ObservedGeneration is the .metadata.generation last reconciled.
	//
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`

	// Conditions:
	//   Linted     — lint phase complete; findings populated.
	//   Approved   — plan passed all matched SchemaPolicies + admission gate.
	//   Executing  — at least one MigrationExecution has been created.
	//   Succeeded  — every spawned MigrationExecution is Succeeded.
	//
	// +optional
	// +patchMergeKey=type
	// +patchStrategy=merge
	// +listType=map
	// +listMapKey=type
	Conditions []metav1.Condition `json:"conditions,omitempty" patchStrategy:"merge" patchMergeKey:"type"`

	// ExecutionRef is the MigrationExecution that this plan spawned.
	// Empty until the plan is approved and an execution is created.
	//
	// +optional
	// +kubebuilder:validation:MaxLength=253
	ExecutionRef string `json:"executionRef,omitempty"`

	// ApprovalMode is the effective mode the MigrationPlanReconciler
	// resolved from matched SchemaPolicies. Populated on every
	// reconcile. Observability-only — the authoritative gate is
	// spec.approved.
	//
	// +optional
	ApprovalMode PlanApprovalMode `json:"approvalMode,omitempty"`

	// ApprovalPolicyName names the SchemaPolicy that selected the
	// current approvalMode. Empty when no matched policy declared
	// planApproval (i.e. the default Auto was taken). Useful for
	// answering "why is this plan waiting?" from kubectl describe.
	//
	// +optional
	// +kubebuilder:validation:MaxLength=253
	ApprovalPolicyName string `json:"approvalPolicyName,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:resource:scope=Namespaced,shortName=mp;plan
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Bundle",type="string",JSONPath=".spec.bundleRef"
// +kubebuilder:printcolumn:name="Version",type="string",JSONPath=".spec.bundleVersion"
// +kubebuilder:printcolumn:name="Schema",type="string",JSONPath=".spec.schemaRef"
// +kubebuilder:printcolumn:name="Statements",type="integer",JSONPath=".spec.statements[*]"
// +kubebuilder:printcolumn:name="Approved",type="boolean",JSONPath=".spec.approved"
// +kubebuilder:printcolumn:name="Mode",type="string",JSONPath=".status.approvalMode"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"

// MigrationPlan is a controller-generated dry-run snapshot for one
// (MigrationBundle, DatabaseSchema) pair. Users do not create these
// directly; reviewers use them to inspect what is about to happen.
type MigrationPlan struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   MigrationPlanSpec   `json:"spec,omitempty"`
	Status MigrationPlanStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MigrationPlanList is the list wrapper required by client-go.
type MigrationPlanList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MigrationPlan `json:"items"`
}

func init() {
	SchemeBuilder.Register(&MigrationPlan{}, &MigrationPlanList{})
}
